/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdvisorRouteImport } from './routes/advisor'
import { Route as AnalysisRouteImport } from './routes/analysis'
import { Route as CompetitorsRouteImport } from './routes/competitors'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as AnalysisAlertsRouteImport } from './routes/analysis/alerts'
import { Route as AnalysisTrendsRouteImport } from './routes/analysis/trends'
import { Route as AnalysisWeeklyReportRouteImport } from './routes/analysis/weekly-report'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvisorRoute = AdvisorRouteImport.update({
  id: '/advisor',
  path: '/advisor',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysisRoute = AnalysisRouteImport.update({
  id: '/analysis',
  path: '/analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const CompetitorsRoute = CompetitorsRouteImport.update({
  id: '/competitors',
  path: '/competitors',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysisAlertsRoute = AnalysisAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AnalysisRoute,
} as any)
const AnalysisTrendsRoute = AnalysisTrendsRouteImport.update({
  id: '/trends',
  path: '/trends',
  getParentRoute: () => AnalysisRoute,
} as any)
const AnalysisWeeklyReportRoute = AnalysisWeeklyReportRouteImport.update({
  id: '/weekly-report',
  path: '/weekly-report',
  getParentRoute: () => AnalysisRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/advisor': typeof AdvisorRoute
  '/analysis': typeof AnalysisRouteWithChildren
  '/competitors': typeof CompetitorsRoute
  '/pricing': typeof PricingRoute
  '/settings': typeof SettingsRoute
  '/analysis/alerts': typeof AnalysisAlertsRoute
  '/analysis/trends': typeof AnalysisTrendsRoute
  '/analysis/weekly-report': typeof AnalysisWeeklyReportRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/advisor': typeof AdvisorRoute
  '/analysis': typeof AnalysisRouteWithChildren
  '/competitors': typeof CompetitorsRoute
  '/pricing': typeof PricingRoute
  '/settings': typeof SettingsRoute
  '/analysis/alerts': typeof AnalysisAlertsRoute
  '/analysis/trends': typeof AnalysisTrendsRoute
  '/analysis/weekly-report': typeof AnalysisWeeklyReportRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/advisor': typeof AdvisorRoute
  '/analysis': typeof AnalysisRouteWithChildren
  '/competitors': typeof CompetitorsRoute
  '/pricing': typeof PricingRoute
  '/settings': typeof SettingsRoute
  '/analysis/alerts': typeof AnalysisAlertsRoute
  '/analysis/trends': typeof AnalysisTrendsRoute
  '/analysis/weekly-report': typeof AnalysisWeeklyReportRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/advisor'
    | '/analysis'
    | '/competitors'
    | '/pricing'
    | '/settings'
    | '/analysis/alerts'
    | '/analysis/trends'
    | '/analysis/weekly-report'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/advisor'
    | '/analysis'
    | '/competitors'
    | '/pricing'
    | '/settings'
    | '/analysis/alerts'
    | '/analysis/trends'
    | '/analysis/weekly-report'
  id:
    | '__root__'
    | '/'
    | '/advisor'
    | '/analysis'
    | '/competitors'
    | '/pricing'
    | '/settings'
    | '/analysis/alerts'
    | '/analysis/trends'
    | '/analysis/weekly-report'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdvisorRoute: typeof AdvisorRoute
  AnalysisRoute: typeof AnalysisRouteWithChildren
  CompetitorsRoute: typeof CompetitorsRoute
  PricingRoute: typeof PricingRoute
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advisor': {
      id: '/advisor'
      path: '/advisor'
      fullPath: '/advisor'
      preLoaderRoute: typeof AdvisorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analysis': {
      id: '/analysis'
      path: '/analysis'
      fullPath: '/analysis'
      preLoaderRoute: typeof AnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/competitors': {
      id: '/competitors'
      path: '/competitors'
      fullPath: '/competitors'
      preLoaderRoute: typeof CompetitorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analysis/alerts': {
      id: '/analysis/alerts'
      path: '/alerts'
      fullPath: '/analysis/alerts'
      preLoaderRoute: typeof AnalysisAlertsRouteImport
      parentRoute: typeof AnalysisRoute
    }
    '/analysis/trends': {
      id: '/analysis/trends'
      path: '/trends'
      fullPath: '/analysis/trends'
      preLoaderRoute: typeof AnalysisTrendsRouteImport
      parentRoute: typeof AnalysisRoute
    }
    '/analysis/weekly-report': {
      id: '/analysis/weekly-report'
      path: '/weekly-report'
      fullPath: '/analysis/weekly-report'
      preLoaderRoute: typeof AnalysisWeeklyReportRouteImport
      parentRoute: typeof AnalysisRoute
    }
  }
}

interface AnalysisRouteChildren {
  AnalysisAlertsRoute: typeof AnalysisAlertsRoute
  AnalysisTrendsRoute: typeof AnalysisTrendsRoute
  AnalysisWeeklyReportRoute: typeof AnalysisWeeklyReportRoute
}

const AnalysisRouteChildren: AnalysisRouteChildren = {
  AnalysisAlertsRoute: AnalysisAlertsRoute,
  AnalysisTrendsRoute: AnalysisTrendsRoute,
  AnalysisWeeklyReportRoute: AnalysisWeeklyReportRoute,
}

const AnalysisRouteWithChildren = AnalysisRoute._addFileChildren(
  AnalysisRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdvisorRoute: AdvisorRoute,
  AnalysisRoute: AnalysisRouteWithChildren,
  CompetitorsRoute: CompetitorsRoute,
  PricingRoute: PricingRoute,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
